apiVersion: v1
kind: Pod
metadata:
  name: redis-cred-vol
spec:
  volumes:
  - name: redis-cred
    secret:
      secretName: secret-creds
      
  containers:
  - image: redis
    name: redis-cont
    volumeMounts:
    - name: redis-cred
      mountPath: /app-creds
    env:
    - name: SENSITIVE
      valueFrom:
        secretKeyRef:
          name: secret-creds
          key: credential  
        

