apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx-test-rc
  name: nginx-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test-rc
    spec:
      containers:
      - image: nginx
        name: nginx-test-rc
        ports:
        - containerPort: 80
---          
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-test-rc
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-test-rc
  type: NodePort
