apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: taska-nginx
  name: taska-nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taska-nginx
  template:
    metadata:
      labels:
        app: taska-nginx
    spec:
      containers:
      - image: nginx
        name: nginx-container
        ports:
        - containerPort: 80
          protocol: TCP
---          
apiVersion: v1
kind: Service
metadata:
  labels:
    run: taska-nginx
  name: taska-nginx-service
spec:
  type: NodePort      
  ports:
  - port: 81
    protocol: TCP
    targetPort: 80
  selector:
    app: taska-nginx
