apiVersion: v1
kind: PersistentVolume
metadata:
  name: w-data 
spec:
  storageClassName: manual
  capacity:
    storage: 0.2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/app-data
    
