apiVersion: v1
kind: Pod
metadata: 
  name: nginx-app
  labels:
    app: nginx
spec:
  nodeSelector:
    vol-mount: app-data-vol 
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: app-data-claim
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: pvc-volume
      mountPath: "/usr/share/nginx/html"

  
