apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath-pod
  labels:
    app: nginx
spec:
  volumes:
  - name: data
    hostPath:
      path: "/web-content" 

  containers:
  - image: nginx:1.14.0
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    
    volumeMounts:
    - name: data
      mountPath: "/usr/share/nginx/html"

  nodeSelector:
    type: "web"
    


      

