apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  labels:
    app: nfs-pv
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 5Gi
  nfs:
    server: 165.22.176.224
    path: /data
