apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
  labels:
    app: nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: nfs-pv

       
